language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
  # npm: false
script:
  npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "steam-neptune"
  local_dir: dist
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
